# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-mingw:
    strategy:
      matrix:
        arch: [x86_64]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-cmake
            unzip
            git

      - name: Build
        shell: msys2 {0}
        run: >
          cmake 
          -G Ninja 
          -DCMAKE_C_COMPILER=clang 
          -DCMAKE_CXX_COMPILER=clang++ 
          -DCMAKE_BUILD_TYPE=Debug 
          -B build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-msys
          path: ./build/
          
  build-ubuntu:
    strategy:
      matrix:
        arch: [x86_64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake clang ninja-build

      - name: Build
        run: >
          cmake 
          -G Ninja 
          -DCMAKE_C_COMPILER=clang 
          -DCMAKE_CXX_COMPILER=clang++ 
          -DCMAKE_BUILD_TYPE=Debug 
          -B build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-ubuntu
          path: ./build/
